### PR TITLE
routes are spilited into seperate files and proper file structure is …

### PR DESCRIPTION
**Pull request by saravanan10393**
Routes were moved into separate files and directory structure is changed for future development. 

Used a ES6 syntaxes for code simplicity. Also updated the README.ME

### CODE REVIEW

**Comment by chanakaDe** [comment]
Did you check the whole project ? everything is running as it was like earlier ? No issues ?

**Comment by saravanan10393** [comment]
I tested it. Will give you a test suit soon . waiting for next issues

**Comment by chanakaDe** [comment]
Great :+1:

**Comment by chanakaDe** [comment]
@saravanan10393  How you implemented the forgot password ?
You send the password to user via email or any new email resetting view ?
Can you explain me please

**Comment by saravanan10393** [comment]
For now email will go with url appended with token.

**Comment by saravanan10393** [comment]
When user clicks on it from UI side guys have to show UI to reset password
and call the patch method of user api

**Pull request merged**
